name:                haskell-training
version:             0.1.0.0
homepage:            https://github.com/tweag/haskell-training#readme
license:             CC-BY-NC-4.0
author:              Marco Perone
maintainer:          marco.perone@tweag.io
copyright:           2022 Tweag I/O
extra-source-files:
- README.md

dependencies:
  - aeson
  - base >= 4.7 && < 5
  - bytestring
  - hasql
  - openapi3
  - rel8
  - servant
  - servant-server
  - text
  - transformers
  - uuid

ghc-options:
  -W
  -fwrite-ide-info
  -hiedir=.hie

library:
  source-dirs:      src

executables:
  forms:
    source-dirs:    forms
    main:           Main.hs
    dependencies:
      - haskell-training
      - warp

  openapi:
    source-dirs:    openapi
    main:           Main.hs
    dependencies:
      - haskell-training
      - aeson-pretty
      - bytestring
      - servant-openapi3

tests:
  forms-spec:
    main:           Spec.hs
    source-dirs:    spec
    dependencies:
      - haskell-training
      - hspec
      - QuickCheck

  forms-doctest:
    source-dirs:      test
    main:             doctests.hs
    ghc-options:      -threaded
    dependencies:
      - haskell-training
      - doctest-parallel >= 0.1
